/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/mention-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * mention 후보 조회
         * @description mention 후보 조회
         */
        get: operations["Mention mention \uD6C4\uBCF4 \uC870\uD68C \uC815\uC0C1 \uC870\uD68C \uC2DC 200 \uACFC \uBCFC \uC218 \uC788\uB294 \uC0AC\uC6A9\uC790 \uBAA9\uB85D\uC744 \uBC18\uD658\uD55C\uB2E4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 페이지 검색
         * @description 페이지 검색
         */
        get: operations["Page \uD398\uC774\uC9C0 \uAC80\uC0C9 \uC815\uC0C1 \uAC80\uC0C9 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 스페이스 목록 조회
         * @description 스페이스 목록 조회
         */
        get: operations["Space \uC2A4\uD398\uC774\uC2A4 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uC870\uB9BD\uB41C \uBAA9\uB85D\uC744 \uBC18\uD658\uD55C\uB2E4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 사용자 검색
         * @description 사용자 검색
         */
        get: operations["User \uC0AC\uC6A9\uC790 \uAC80\uC0C9 \uC815\uC0C1 \uAC80\uC0C9 \uC2DC 200 \uACFC \uB9E4\uCE6D \uACB0\uACFC + \uC18C\uC18D \uC2A4\uD398\uC774\uC2A4 \uC9D1\uD569"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pages/{pageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 페이지 단건 조회
         * @description 페이지 단건 조회
         */
        get: operations["Page \uD398\uC774\uC9C0 \uB2E8\uAC74 \uC870\uD68C \uC874\uC7AC\uD558\uBA74 200 \uACFC \uC815\uBCF4\uB97C \uBC18\uD658\uD55C\uB2E4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pages/{pageId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 댓글 목록 조회
         * @description 댓글 목록 조회
         */
        get: operations["Comment \uB313\uAE00 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4"];
        put?: never;
        /**
         * 댓글 등록
         * @description 댓글 등록
         */
        post: operations["Comment \uB313\uAE00 \uB4F1\uB85D \uC815\uC0C1 \uC0DD\uC131 \uC2DC 201 \uACFC commentId \uB97C \uBC18\uD658\uD55C\uB2E4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pages/{pageId}/inbound": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 페이지 인바운드 링크 목록 조회
         * @description 페이지 인바운드 링크 목록 조회
         */
        get: operations["Page \uD398\uC774\uC9C0 \uC778\uBC14\uC6B4\uB4DC \uB9C1\uD06C \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces/{spaceId}/audit-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 스페이스 감사 이력 조회
         * @description 스페이스 감사 이력 조회
         */
        get: operations["SpaceAudit \uC2A4\uD398\uC774\uC2A4 \uAC10\uC0AC \uC774\uB825 \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uCD5C\uC2E0\uC21C \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces/{spaceId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 스페이스 멤버 목록 조회
         * @description 스페이스 멤버 목록 조회
         */
        get: operations["SpaceMember \uC2A4\uD398\uC774\uC2A4 \uBA64\uBC84 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pages/{pageId}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 댓글 단건 조회
         * @description 댓글 단건 조회
         */
        get: operations["Comment \uB313\uAE00 \uB2E8\uAC74 \uC870\uD68C \uC874\uC7AC\uD558\uBA74 200 \uACFC \uC815\uBCF4\uB97C \uBC18\uD658\uD55C\uB2E4"];
        /**
         * 댓글 수정
         * @description 댓글 수정
         */
        put: operations["Comment \uB313\uAE00 \uC218\uC815 \uBCF8\uBB38 \uBCC0\uACBD \uC2DC 200 \uACFC \uAC31\uC2E0 \uACB0\uACFC\uB97C \uBC18\uD658\uD55C\uB2E4"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** PageGetResponse */
        PageGetResponse: {
            /**
             * @description 페이지 공개 범위＊
             * @enum {string}
             */
            visibility: "DRAFT" | "INTERNAL" | "MEMBER" | "PUBLIC";
            /** @description 현재 viewer 가 이 페이지를 수정할 수 있는지. ADMIN 글로벌 권한 또는 (author 본인 && 스페이스 쓰기 권한) 일 때 true.＊ */
            canEdit: boolean;
            /** @description 부모 페이지 식별자 */
            parentPageId?: string | null;
            /** @description 같은 부모 내 표시 순서 (0 부터 시작, 작을수록 앞)＊ */
            displayOrder: number;
            /** @description 작성자 사용자 이름 (삭제된 사용자의 경우 빈 문자열)＊ */
            authorHandle: string;
            /** @description 제목＊ */
            title: string;
            /** @description 작성자 식별자＊ */
            authorId: string;
            /** @description 페이지 식별자＊ */
            pageId: string;
            /** @description 현재 버전＊ */
            currentVersion: number;
            /** @description 본문 (TipTap JSON 문자열). `{type:'pageLink', attrs:{pageId, displayText}}` 노드의 target 이 viewer 의 visibility scope 와 안 맞으면 attrs.displayText 가 `비공개 페이지` 로 마스킹된다 (pageId 는 보존).＊ */
            content: string;
            /** @description 생성 시각 (ISO)＊ */
            createdAt: string;
            /** @description 소속 스페이스 식별자＊ */
            spaceId: string;
            /** @description 현재 viewer 가 이 페이지에 댓글을 남길 수 있는지. 로그인 상태이면 true (본 응답을 받은 viewer 는 페이지를 GET 한 reader 임이 보장됨). 비로그인은 false.＊ */
            canComment: boolean;
            /** @description 조상 페이지 목록 — root → 직계 부모 순서＊ */
            ancestors: {
                /** @description ⎯ 조상 페이지 제목＊ */
                title: string;
                /** @description ⎯ 조상 페이지 식별자＊ */
                pageId: string;
            }[];
            /** @description 최근 갱신 시각 (ISO)＊ */
            updatedAt: string;
        };
        /** SpaceAuditEntryListResponse */
        SpaceAuditEntryListResponse: {
            /** @description 페이지당 항목 수＊ */
            size: number;
            /** @description 결과 비어 있음 여부＊ */
            isEmpty: boolean;
            /** @description 총 페이지 수＊ */
            totalPages: number;
            /** @description 다음 페이지 존재 여부＊ */
            hasNext: boolean;
            /** @description 현재 페이지＊ */
            page: number;
            /** @description 감사 이력 목록＊ */
            items: {
                /** @description ⎯ 발생 시각 (ISO)＊ */
                createdAt: string;
                /** @description ⎯ 변경 주체 사용자 식별자＊ */
                actorUserId: string;
                /** @description ⎯ 변경 유형 (REGISTERED / EDITED / DELETED)＊ */
                action: string;
                /** @description ⎯ 감사 이력 식별자＊ */
                id: string;
                /** @description ⎯ 변경 요약 JSON 문자열＊ */
                changeSummary: string;
                /** @description ⎯ 변경 주체 handle (조회 miss 시 빈 문자열)＊ */
                actorHandle: string;
            }[];
            /** @description 총 항목 수＊ */
            totalElements: number;
        };
        /** PageSearchResponse */
        PageSearchResponse: {
            /** @description 페이지당 항목 수＊ */
            size: number;
            /** @description 결과 비어 있음 여부＊ */
            isEmpty: boolean;
            /** @description 총 페이지 수＊ */
            totalPages: number;
            /** @description 다음 페이지 존재 여부＊ */
            hasNext: boolean;
            /** @description 현재 페이지＊ */
            page: number;
            /** @description 검색 결과 목록＊ */
            items: {
                /** @description ⎯ 소속 스페이스 식별자＊ */
                spaceId: string;
                /**
                 * @description ⎯ 페이지 공개 범위＊
                 * @enum {string}
                 */
                visibility: "DRAFT" | "INTERNAL" | "MEMBER" | "PUBLIC";
                /** @description ⎯ 부모 페이지 식별자 */
                parentPageId?: string | null;
                /** @description ⎯ 같은 부모 내 표시 순서 (0 부터 시작, 작을수록 앞)＊ */
                displayOrder: number;
                /** @description ⎯ 작성자 사용자 이름 (삭제된 사용자의 경우 빈 문자열)＊ */
                authorHandle: string;
                /** @description ⎯ 제목＊ */
                title: string;
                /** @description ⎯ 작성자 식별자＊ */
                authorId: string;
                /** @description ⎯ 페이지 식별자＊ */
                pageId: string;
                /** @description ⎯ 최근 갱신 시각 (ISO)＊ */
                updatedAt: string;
            }[];
            /** @description 총 항목 수＊ */
            totalElements: number;
        };
        /** MentionCandidateGetResponse */
        MentionCandidateGetResponse: {
            /** @description mention 가능한 사용자 목록＊ */
            items: {
                /** @description ⎯ 사용자 이름＊ */
                handle: string;
                /** @description ⎯ 사용자 식별자＊ */
                userId: string;
            }[];
        };
        /** SpaceMemberListResponse */
        SpaceMemberListResponse: {
            /** @description 페이지당 항목 수＊ */
            size: number;
            /** @description 결과 비어 있음 여부＊ */
            isEmpty: boolean;
            /** @description 총 페이지 수＊ */
            totalPages: number;
            /** @description 다음 페이지 존재 여부＊ */
            hasNext: boolean;
            /** @description 현재 페이지＊ */
            page: number;
            /** @description 멤버 목록＊ */
            items: {
                /** @description ⎯ 스페이스 식별자＊ */
                spaceId: string;
                /** @description ⎯ 역할＊ */
                role: string;
                /** @description ⎯ 가입 시각 (ISO)＊ */
                joinedAt: string;
                /** @description ⎯ 사용자 handle (사용자 조회 miss 시 빈 문자열)＊ */
                handle: string;
                /** @description ⎯ 멤버 식별자＊ */
                spaceMemberId: string;
                /** @description ⎯ 사용자 식별자＊ */
                userId: string;
            }[];
            /** @description 총 항목 수＊ */
            totalElements: number;
        };
        /** UserSearchResponse */
        UserSearchResponse: {
            /** @description 매칭된 사용자 목록＊ */
            items: {
                /** @description ⎯ 사용자가 소속된 스페이스 식별자 목록 (검색자가 볼 수 있는 스페이스만 노출, SpaceId 오름차순, 없으면 빈 배열)＊ */
                memberOfSpaceIds: (Record<string, never> | boolean | string | number)[];
                /** @description ⎯ 요청 spaceId 에 이미 참여 중인지 여부. spaceId 미지정 또는 검색자가 해당 스페이스를 볼 수 없으면 null. */
                alreadyMember?: boolean | null;
                /** @description ⎯ 사용자 이름＊ */
                handle: string;
                /** @description ⎯ 사용자 식별자＊ */
                userId: string;
            }[];
        };
        /** PageInboundLinkListResponse */
        PageInboundLinkListResponse: {
            /** @description 페이지당 항목 수＊ */
            size: number;
            /** @description 결과 비어 있음 여부＊ */
            isEmpty: boolean;
            /** @description 총 페이지 수＊ */
            totalPages: number;
            /** @description 다음 페이지 존재 여부＊ */
            hasNext: boolean;
            /** @description 현재 페이지＊ */
            page: number;
            /** @description 인바운드 링크 source 목록＊ */
            items: {
                /** @description ⎯ source 페이지 소속 스페이스＊ */
                spaceId: string;
                /** @description ⎯ PUBLIC / INTERNAL / DRAFT＊ */
                visibility: string;
                /** @description ⎯ 부모 페이지 식별자 */
                parentPageId?: string | null;
                /** @description ⎯ 스페이스 내 정렬 순서＊ */
                displayOrder: number;
                /** @description ⎯ 작성자 핸들 — 알 수 없으면 빈 문자열＊ */
                authorHandle: string;
                /** @description ⎯ source 페이지 제목＊ */
                title: string;
                /** @description ⎯ 작성자 식별자＊ */
                authorId: string;
                /** @description ⎯ source 페이지 식별자＊ */
                pageId: string;
                /** @description ⎯ source 페이지 최종 수정 시각 (ISO)＊ */
                updatedAt: string;
            }[];
            /** @description 총 항목 수＊ */
            totalElements: number;
        };
        /** CommentEditRequest */
        CommentEditRequest: {
            /** @description 수정된 본문 (TipTap JSON)＊ */
            content: string;
        };
        /** CommentEditResponse */
        CommentEditResponse: {
            /** @description 댓글 식별자＊ */
            commentId: string;
            /** @description 작성자 사용자 이름 (삭제된 사용자의 경우 빈 문자열)＊ */
            authorHandle: string;
            /** @description 갱신된 본문 (TipTap JSON)＊ */
            content: string;
            /** @description 갱신 시각 (ISO)＊ */
            updatedAt: string;
        };
        /** CommentListResponse */
        CommentListResponse: {
            /** @description 페이지당 항목 수＊ */
            size: number;
            /** @description 결과 비어 있음 여부＊ */
            isEmpty: boolean;
            /** @description 총 페이지 수＊ */
            totalPages: number;
            /** @description 다음 페이지 존재 여부＊ */
            hasNext: boolean;
            /** @description 현재 페이지＊ */
            page: number;
            /** @description 댓글 목록＊ */
            items: {
                /** @description ⎯ 생성 시각 (ISO)＊ */
                createdAt: string;
                /** @description ⎯ 현재 viewer 가 이 댓글을 수정할 수 있는지. ADMIN 글로벌 권한 또는 (author 본인 && 스페이스 쓰기 권한) 일 때 true.＊ */
                canEdit: boolean;
                /** @description ⎯ 댓글 식별자＊ */
                commentId: string;
                /** @description ⎯ 작성자 사용자 이름 (삭제된 사용자의 경우 빈 문자열)＊ */
                authorHandle: string;
                /** @description ⎯ 작성자 식별자＊ */
                authorId: string;
                /** @description ⎯ 소속 페이지 식별자＊ */
                pageId: string;
                /** @description ⎯ 본문 (TipTap JSON)＊ */
                content: string;
                /** @description ⎯ 최근 갱신 시각 (ISO)＊ */
                updatedAt: string;
            }[];
            /** @description 총 항목 수＊ */
            totalElements: number;
        };
        /** CommentRegisterRequest */
        CommentRegisterRequest: {
            /** @description 댓글 본문 (TipTap JSON)＊ */
            content: string;
        };
        /** SpaceListResponse */
        SpaceListResponse: {
            /** @description 페이지당 항목 수＊ */
            size: number;
            /** @description 결과 비어 있음 여부＊ */
            isEmpty: boolean;
            /** @description 총 페이지 수＊ */
            totalPages: number;
            /** @description 다음 페이지 존재 여부＊ */
            hasNext: boolean;
            /** @description 현재 페이지＊ */
            page: number;
            /** @description 스페이스 목록＊ */
            items: {
                /** @description ⎯ 스페이스 생성 시각 (ISO)＊ */
                createdAt: string;
                /** @description ⎯ 스페이스 식별자＊ */
                spaceId: string;
                /** @description ⎯ viewer 가 볼 수 있는 페이지 수 (lookup 실패 시 0)＊ */
                pageCount: number;
                /**
                 * @description ⎯ 현재 viewer 의 role (Anonymous / 비-멤버는 null)
                 * @enum {string|null}
                 */
                myRole?: "OWNER" | "MEMBER" | "VIEWER" | null;
                /**
                 * @description ⎯ 스페이스 공개 범위＊
                 * @enum {string}
                 */
                visibility: "INTERNAL" | "PUBLIC";
                /** @description ⎯ 스페이스 멤버 수 (lookup 실패 시 0)＊ */
                memberCount: number;
                /** @description ⎯ 스페이스 이름＊ */
                name: string;
                /** @description ⎯ 스페이스 설명＊ */
                description: string;
                /** @description ⎯ MAX(space.updatedAt, latestPage.updatedAt), 페이지 없으면 space.updatedAt (ISO)＊ */
                lastActivityAt: string;
                /** @description ⎯ viewer 가 볼 수 있는 최근 편집 페이지 (없거나 lookup 실패 시 null) */
                latestPage?: {
                    /** @description ⎯ ⎯ 페이지 제목＊ */
                    title: string;
                    /** @description ⎯ ⎯ 페이지 식별자＊ */
                    pageId: string;
                    /** @description ⎯ ⎯ 페이지 편집 시각 (ISO)＊ */
                    updatedAt: string;
                };
                /** @description ⎯ 스페이스 갱신 시각 (ISO)＊ */
                updatedAt: string;
            }[];
            /** @description 총 항목 수＊ */
            totalElements: number;
        };
        /** CommentRegisterResponse */
        CommentRegisterResponse: {
            /** @description 생성된 댓글 식별자＊ */
            commentId: string;
            /** @description 작성자 사용자 이름 (삭제된 사용자의 경우 빈 문자열)＊ */
            authorHandle: string;
        };
        /** CommentGetResponse */
        CommentGetResponse: {
            /** @description 생성 시각 (ISO)＊ */
            createdAt: string;
            /** @description 현재 viewer 가 이 댓글을 수정할 수 있는지. ADMIN 글로벌 권한 또는 (author 본인 && 스페이스 쓰기 권한) 일 때 true.＊ */
            canEdit: boolean;
            /** @description 댓글 식별자＊ */
            commentId: string;
            /** @description 작성자 사용자 이름 (삭제된 사용자의 경우 빈 문자열)＊ */
            authorHandle: string;
            /** @description 작성자 식별자＊ */
            authorId: string;
            /** @description 소속 페이지 식별자＊ */
            pageId: string;
            /** @description 본문 (TipTap JSON)＊ */
            content: string;
            /** @description 최근 갱신 시각 (ISO)＊ */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "Mention mention \uD6C4\uBCF4 \uC870\uD68C \uC815\uC0C1 \uC870\uD68C \uC2DC 200 \uACFC \uBCFC \uC218 \uC788\uB294 \uC0AC\uC6A9\uC790 \uBAA9\uB85D\uC744 \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query: {
                /** @description 검색어 (handle 부분 일치, 대소문자 무시, 1~30자) */
                query: string;
                /** @description 결과 수 (1 ~ 20, 기본값 10) */
                size?: string;
                /** @description 편집 중인 페이지가 속한 스페이스 식별자 */
                spaceId: string;
                /** @description 스페이스 공개 범위 (INTERNAL, PUBLIC). 편집 중 미저장 상태를 반영하기 위해 클라이언트가 명시. */
                spaceVisibility: string;
                /** @description 페이지 공개 범위 (DRAFT, INTERNAL, MEMBER, PUBLIC). 편집 중 미저장 상태를 반영하기 위해 클라이언트가 명시. */
                pageVisibility: string;
                /** @description 편집 중인 페이지 작성자 식별자 */
                pageAuthorId: string;
            };
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MentionCandidateGetResponse"];
                };
            };
        };
    };
    "Page \uD398\uC774\uC9C0 \uAC80\uC0C9 \uC815\uC0C1 \uAC80\uC0C9 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: {
                /** @description 검색 키워드 (제목·본문, 대소문자 무시) */
                query?: string;
                /** @description 스페이스 ID 필터 */
                space?: string;
                /** @description 태그 ID 필터 (다중 시 AND 매칭) */
                tag?: string;
                /** @description 태그 이름 필터 (cross-space 같은 이름의 모든 태그 중 하나 이상 보유, 미매치 시 빈 결과) */
                tagName?: string;
                /** @description 정렬 옵션 (CREATED_AT / UPDATED_AT / RELEVANCE / TREE, 기본값 UPDATED_AT) */
                sort?: string;
                /** @description 부모 페이지 ID 필터 (해당 부모의 직계 자녀만 반환, onlyRoot 와 상호 배타) */
                parentPageId?: string;
                /** @description 루트 페이지 (parentPageId 가 null) 만 반환. 기본값 false, parentPageId 와 상호 배타 */
                onlyRoot?: string;
                /** @description 페이지 */
                page?: string;
                /** @description 페이지당 항목 수 */
                size?: string;
            };
            header?: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageSearchResponse"];
                };
            };
        };
    };
    "Space \uC2A4\uD398\uC774\uC2A4 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uC870\uB9BD\uB41C \uBAA9\uB85D\uC744 \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: {
                /** @description 페이지 */
                page?: string;
                /** @description 페이지당 항목 수 */
                size?: string;
            };
            header?: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceListResponse"];
                };
            };
        };
    };
    "User \uC0AC\uC6A9\uC790 \uAC80\uC0C9 \uC815\uC0C1 \uAC80\uC0C9 \uC2DC 200 \uACFC \uB9E4\uCE6D \uACB0\uACFC + \uC18C\uC18D \uC2A4\uD398\uC774\uC2A4 \uC9D1\uD569": {
        parameters: {
            query: {
                /** @description 검색어 (handle 부분 일치, 대소문자 무시, 1~30자) */
                query: string;
                /** @description 결과 수 (1 ~ 20, 기본값 10) */
                size?: string;
                /** @description 초대 대상 스페이스 식별자. 지정 시 각 item 의 alreadyMember 가 true/false 로 채워진다. 지정 시 Long 형식이어야 하며, 빈 값이면 400. */
                spaceId?: string;
            };
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSearchResponse"];
                };
            };
        };
    };
    "Page \uD398\uC774\uC9C0 \uB2E8\uAC74 \uC870\uD68C \uC874\uC7AC\uD558\uBA74 200 \uACFC \uC815\uBCF4\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization?: string;
            };
            path: {
                pageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageGetResponse"];
                };
            };
        };
    };
    "Comment \uB313\uAE00 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: {
                /** @description 페이지 */
                page?: string;
                /** @description 페이지당 항목 수 */
                size?: string;
            };
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                pageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentListResponse"];
                };
            };
        };
    };
    "Comment \uB313\uAE00 \uB4F1\uB85D \uC815\uC0C1 \uC0DD\uC131 \uC2DC 201 \uACFC commentId \uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                pageId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["CommentRegisterRequest"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentRegisterResponse"];
                };
            };
        };
    };
    "Page \uD398\uC774\uC9C0 \uC778\uBC14\uC6B4\uB4DC \uB9C1\uD06C \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: {
                /** @description 페이지 */
                page?: string;
                /** @description 페이지당 항목 수 */
                size?: string;
            };
            header?: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization?: string;
            };
            path: {
                pageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageInboundLinkListResponse"];
                };
            };
        };
    };
    "SpaceAudit \uC2A4\uD398\uC774\uC2A4 \uAC10\uC0AC \uC774\uB825 \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uCD5C\uC2E0\uC21C \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: {
                /** @description 페이지 */
                page?: string;
                /** @description 페이지당 항목 수 */
                size?: string;
            };
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                spaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceAuditEntryListResponse"];
                };
            };
        };
    };
    "SpaceMember \uC2A4\uD398\uC774\uC2A4 \uBA64\uBC84 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: {
                /** @description 페이지 */
                page?: string;
                /** @description 페이지당 항목 수 */
                size?: string;
            };
            header?: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization?: string;
            };
            path: {
                spaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceMemberListResponse"];
                };
            };
        };
    };
    "Comment \uB313\uAE00 \uB2E8\uAC74 \uC870\uD68C \uC874\uC7AC\uD558\uBA74 200 \uACFC \uC815\uBCF4\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                pageId: string;
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentGetResponse"];
                };
            };
        };
    };
    "Comment \uB313\uAE00 \uC218\uC815 \uBCF8\uBB38 \uBCC0\uACBD \uC2DC 200 \uACFC \uAC31\uC2E0 \uACB0\uACFC\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                pageId: string;
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["CommentEditRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentEditResponse"];
                };
            };
        };
    };
}
