/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원가입
         * @description 회원가입
         */
        post: operations["User \uD68C\uC6D0\uAC00\uC785 \uC815\uC0C1 \uAC00\uC785 \uC2DC 201 \uACFC userId/token \uC744 \uBC18\uD658\uD55C\uB2E4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 로그인
         */
        post: operations["Auth \uB85C\uADF8\uC778 \uC815\uC0C1 \uB85C\uADF8\uC778 \uC2DC 200 \uACFC userId/token \uC744 \uBC18\uD658\uD55C\uB2E4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 로그아웃
         */
        post: operations["Auth \uB85C\uADF8\uC544\uC6C3 \uC815\uC0C1 \uD1A0\uD070\uC744 \uBC1B\uC73C\uBA74 204 \uB97C \uBC18\uD658\uD55C\uB2E4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "v1-users1255392465": {
            /** @description 생성된 사용자 식별자＊ */
            userId: string;
            /** @description 발급된 세션 토큰＊ */
            token: string;
        };
        "v1-auth-logout1664319328": {
            /** @description revoke 대상 세션 토큰＊ */
            token: string;
        };
        "v1-auth-login298699336": {
            /** @description 비밀번호＊ */
            password: string;
            /** @description 이메일＊ */
            email: string;
        };
        "v1-users1116461201": {
            /** @description 비밀번호＊ */
            password: string;
            /** @description 핸들 (영문 소문자/숫자/_, 3~30자)＊ */
            handle: string;
            /** @description 이메일＊ */
            email: string;
        };
        "v1-auth-login-1893566759": {
            /** @description 사용자 식별자＊ */
            userId: string;
            /** @description 발급된 세션 토큰＊ */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "User \uD68C\uC6D0\uAC00\uC785 \uC815\uC0C1 \uAC00\uC785 \uC2DC 201 \uACFC userId/token \uC744 \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["v1-users1116461201"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-users1255392465"];
                };
            };
        };
    };
    "Auth \uB85C\uADF8\uC778 \uC815\uC0C1 \uB85C\uADF8\uC778 \uC2DC 200 \uACFC userId/token \uC744 \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["v1-auth-login298699336"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-auth-login-1893566759"];
                };
            };
        };
    };
    "Auth \uB85C\uADF8\uC544\uC6C3 \uC815\uC0C1 \uD1A0\uD070\uC744 \uBC1B\uC73C\uBA74 204 \uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["v1-auth-logout1664319328"];
            };
        };
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
