/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 페이지 검색
         * @description 페이지 검색
         */
        get: operations["Page \uD398\uC774\uC9C0 \uAC80\uC0C9 \uC815\uC0C1 \uAC80\uC0C9 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4"];
        put?: never;
        /**
         * 페이지 생성
         * @description 페이지 생성
         */
        post: operations["Page \uD398\uC774\uC9C0 \uC0DD\uC131 \uC815\uC0C1 \uC0DD\uC131 \uC2DC 201 \uACFC pageId \uB97C \uBC18\uD658\uD55C\uB2E4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 스페이스 목록 조회
         * @description 스페이스 목록 조회
         */
        get: operations["Space \uC2A4\uD398\uC774\uC2A4 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4"];
        put?: never;
        /**
         * 스페이스 생성
         * @description 스페이스 생성
         */
        post: operations["Space \uC2A4\uD398\uC774\uC2A4 \uC0DD\uC131 \uC815\uC0C1 \uC0DD\uC131 \uC2DC 201 \uACFC spaceId \uB97C \uBC18\uD658\uD55C\uB2E4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 태그 등록
         * @description 태그 등록
         */
        post: operations["Tag \uD0DC\uADF8 \uB4F1\uB85D \uC815\uC0C1 \uC0DD\uC131 \uC2DC 201 \uACFC tagId \uB97C \uBC18\uD658\uD55C\uB2E4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pages/{pageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 페이지 단건 조회
         * @description 페이지 단건 조회
         */
        get: operations["Page \uD398\uC774\uC9C0 \uB2E8\uAC74 \uC870\uD68C \uC874\uC7AC\uD558\uBA74 200 \uACFC \uC815\uBCF4\uB97C \uBC18\uD658\uD55C\uB2E4"];
        /**
         * 페이지 수정
         * @description 페이지 수정
         */
        put: operations["Page \uD398\uC774\uC9C0 \uC218\uC815 \uC81C\uBAA9\u00B7\uBCF8\uBB38 \uBCC0\uACBD \uC2DC 200 \uACFC \uAC31\uC2E0 \uACB0\uACFC\uB97C \uBC18\uD658\uD55C\uB2E4"];
        post?: never;
        /**
         * 페이지 삭제
         * @description 페이지 삭제
         */
        delete: operations["Page \uD398\uC774\uC9C0 \uC0AD\uC81C \uC131\uACF5\uD558\uBA74 204 \uB97C \uBC18\uD658\uD55C\uB2E4"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces/{spaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 스페이스 단건 조회
         * @description 스페이스 단건 조회
         */
        get: operations["Space \uC2A4\uD398\uC774\uC2A4 \uB2E8\uAC74 \uC870\uD68C \uC874\uC7AC\uD558\uBA74 200 \uACFC \uC815\uBCF4\uB97C \uBC18\uD658\uD55C\uB2E4"];
        /**
         * 스페이스 수정
         * @description 스페이스 수정
         */
        put: operations["Space \uC2A4\uD398\uC774\uC2A4 \uC218\uC815 \uC774\uB984\u00B7\uC124\uBA85\uC744 \uBCC0\uACBD\uD558\uBA74 200 \uACFC \uAC31\uC2E0 \uACB0\uACFC\uB97C \uBC18\uD658\uD55C\uB2E4"];
        post?: never;
        /**
         * 스페이스 삭제
         * @description 스페이스 삭제
         */
        delete: operations["Space \uC2A4\uD398\uC774\uC2A4 \uC0AD\uC81C \uC131\uACF5\uD558\uBA74 204 \uB97C \uBC18\uD658\uD55C\uB2E4"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tags/{tagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 태그 삭제
         * @description 태그 삭제
         */
        delete: operations["Tag \uD0DC\uADF8 \uC0AD\uC81C ADMIN \uC73C\uB85C \uD638\uCD9C\uD558\uBA74 204 \uB97C \uBC18\uD658\uD55C\uB2E4"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pages/{pageId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 댓글 목록 조회
         * @description 댓글 목록 조회
         */
        get: operations["Comment \uB313\uAE00 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4"];
        put?: never;
        /**
         * 댓글 등록
         * @description 댓글 등록
         */
        post: operations["Comment \uB313\uAE00 \uB4F1\uB85D \uC815\uC0C1 \uC0DD\uC131 \uC2DC 201 \uACFC commentId \uB97C \uBC18\uD658\uD55C\uB2E4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pages/{pageId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 페이지 리비전 목록 조회
         * @description 페이지 리비전 목록 조회
         */
        get: operations["Page \uD398\uC774\uC9C0 \uB9AC\uBE44\uC804 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pages/{pageId}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 페이지 태그 목록 조회
         * @description 페이지 태그 목록 조회
         */
        get: operations["Tag \uD398\uC774\uC9C0 \uD0DC\uADF8 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4"];
        put?: never;
        /**
         * 페이지에 태그 매핑
         * @description 페이지에 태그 매핑
         */
        post: operations["Tag \uD398\uC774\uC9C0\uC5D0 \uD0DC\uADF8 \uB9E4\uD551 \uC131\uACF5\uD558\uBA74 204 \uB97C \uBC18\uD658\uD55C\uB2E4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces/{spaceId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 스페이스 멤버 목록 조회
         * @description 스페이스 멤버 목록 조회
         */
        get: operations["SpaceMember \uC2A4\uD398\uC774\uC2A4 \uBA64\uBC84 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4"];
        put?: never;
        /**
         * 스페이스 멤버 가입
         * @description 스페이스 멤버 가입
         */
        post: operations["SpaceMember \uC2A4\uD398\uC774\uC2A4 \uBA64\uBC84 \uAC00\uC785 "];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces/{spaceId}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 스페이스 태그 목록 조회
         * @description 스페이스 태그 목록 조회
         */
        get: operations["Tag \uC2A4\uD398\uC774\uC2A4 \uD0DC\uADF8 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pages/{pageId}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 댓글 단건 조회
         * @description 댓글 단건 조회
         */
        get: operations["Comment \uB313\uAE00 \uB2E8\uAC74 \uC870\uD68C \uC874\uC7AC\uD558\uBA74 200 \uACFC \uC815\uBCF4\uB97C \uBC18\uD658\uD55C\uB2E4"];
        /**
         * 댓글 수정
         * @description 댓글 수정
         */
        put: operations["Comment \uB313\uAE00 \uC218\uC815 \uBCF8\uBB38 \uBCC0\uACBD \uC2DC 200 \uACFC \uAC31\uC2E0 \uACB0\uACFC\uB97C \uBC18\uD658\uD55C\uB2E4"];
        post?: never;
        /**
         * 댓글 삭제
         * @description 댓글 삭제
         */
        delete: operations["Comment \uB313\uAE00 \uC0AD\uC81C \uC131\uACF5\uD558\uBA74 204 \uB97C \uBC18\uD658\uD55C\uB2E4"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pages/{pageId}/revisions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 페이지 리비전 단건 조회
         * @description 페이지 리비전 단건 조회
         */
        get: operations["Page \uD398\uC774\uC9C0 \uB9AC\uBE44\uC804 \uB2E8\uAC74 \uC870\uD68C \uC874\uC7AC\uD558\uBA74 200 \uACFC \uC815\uBCF4\uB97C \uBC18\uD658\uD55C\uB2E4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pages/{pageId}/tags/{tagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 페이지에서 태그 매핑 제거
         * @description 페이지에서 태그 매핑 제거
         */
        delete: operations["Tag \uD398\uC774\uC9C0\uC5D0\uC11C \uD0DC\uADF8 \uB9E4\uD551 \uC81C\uAC70 \uC131\uACF5\uD558\uBA74 204 \uB97C \uBC18\uD658\uD55C\uB2E4"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces/{spaceId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 스페이스 멤버 역할 변경
         * @description 스페이스 멤버 역할 변경
         */
        put: operations["SpaceMember \uC2A4\uD398\uC774\uC2A4 \uBA64\uBC84 \uC5ED\uD560 \uBCC0\uACBD \uC815\uC0C1 \uBCC0\uACBD \uC2DC 200 \uACFC \uAC31\uC2E0\uB41C \uBA64\uBC84 \uC815\uBCF4\uB97C \uBC18\uD658\uD55C\uB2E4"];
        post?: never;
        /**
         * 스페이스 멤버 제거
         * @description 스페이스 멤버 제거
         */
        delete: operations["SpaceMember \uC2A4\uD398\uC774\uC2A4 \uBA64\uBC84 \uC81C\uAC70 \uC131\uACF5\uD558\uBA74 204 \uB97C \uBC18\uD658\uD55C\uB2E4"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "v1-pages-1087482196": {
            /** @description 소속 스페이스 식별자＊ */
            spaceId: string;
            /** @description 공개 범위 (DRAFT / INTERNAL / PUBLIC)＊ */
            visibility: string;
            /** @description 부모 페이지 식별자 */
            parentPageId?: string | null;
            /** @description 제목＊ */
            title: string;
            /** @description 본문 (위키링크 [[...]] 추출 대상)＊ */
            content: string;
        };
        "v1-tags-1141217090": {
            /** @description 생성된 태그 식별자＊ */
            tagId: string;
        };
        "v1-spaces-spaceId-members-userId1005729910": {
            /** @description 스페이스 식별자＊ */
            spaceId: string;
            /** @description 갱신된 역할＊ */
            role: string;
            /** @description 멤버 식별자＊ */
            spaceMemberId: string;
            /** @description 사용자 식별자＊ */
            userId: string;
        };
        "v1-spaces-spaceId175277175": {
            /** @description 변경할 공개 범위 */
            visibility?: string | null;
            /** @description 변경할 이름 */
            name?: string | null;
            /** @description 변경할 설명 */
            description?: string | null;
        };
        "v1-pages-pageId-comments-225807540": {
            /** @description 댓글 본문＊ */
            body: string;
        };
        "v1-spaces-spaceId-members-userId781967196": {
            /** @description 새 역할＊ */
            role: string;
        };
        "v1-spaces-spaceId-6516778": {
            /** @description 생성 시각 (ISO)＊ */
            createdAt: string;
            /** @description 스페이스 식별자＊ */
            spaceId: string;
            /** @description 공개 범위＊ */
            visibility: string;
            /** @description 이름＊ */
            name: string;
            /** @description 설명＊ */
            description: string;
            /** @description 최근 갱신 시각 (ISO)＊ */
            updatedAt: string;
        };
        "v1-spaces1523498116": {
            /** @description 페이지당 항목 수＊ */
            size: number;
            /** @description 결과 비어 있음 여부＊ */
            isEmpty: boolean;
            /** @description 총 페이지 수＊ */
            totalPages: number;
            /** @description 다음 페이지 존재 여부＊ */
            hasNext: boolean;
            /** @description 현재 페이지＊ */
            page: number;
            /** @description 스페이스 목록＊ */
            items: {
                /** @description ⎯ 생성 시각 (ISO)＊ */
                createdAt: string;
                /** @description ⎯ 스페이스 식별자＊ */
                spaceId: string;
                /** @description ⎯ 공개 범위＊ */
                visibility: string;
                /** @description ⎯ 이름＊ */
                name: string;
                /** @description ⎯ 설명＊ */
                description: string;
                /** @description ⎯ 최근 갱신 시각 (ISO)＊ */
                updatedAt: string;
            }[];
            /** @description 총 항목 수＊ */
            totalElements: number;
        };
        "v1-pages-pageId-tags1826217235": {
            /** @description 매핑할 태그 식별자＊ */
            tagId: string;
        };
        "v1-pages-pageId-comments-commentId-1192310110": {
            /** @description 생성 시각 (ISO)＊ */
            createdAt: string;
            /** @description 댓글 식별자＊ */
            commentId: string;
            /** @description 본문＊ */
            body: string;
            /** @description 작성자 식별자＊ */
            authorId: string;
            /** @description 소속 페이지 식별자＊ */
            pageId: string;
            /** @description 최근 갱신 시각 (ISO)＊ */
            updatedAt: string;
        };
        "v1-pages-pageId-comments-1994389907": {
            /** @description 생성된 댓글 식별자＊ */
            commentId: string;
        };
        "v1-spaces-spaceId-members-472001083": {
            /** @description 스페이스 식별자＊ */
            spaceId: string;
            /** @description 부여된 역할＊ */
            role: string;
            /** @description 멤버 식별자＊ */
            spaceMemberId: string;
            /** @description 사용자 식별자＊ */
            userId: string;
        };
        "v1-spaces-1862598174": {
            /** @description 공개 범위 (PUBLIC|INTERNAL)＊ */
            visibility: string;
            /** @description 스페이스 이름＊ */
            name: string;
            /** @description 스페이스 설명＊ */
            description: string;
        };
        "v1-pages-pageId51781261": {
            /** @description 새 제목＊ */
            title: string;
            /** @description 새 본문＊ */
            content: string;
        };
        "v1-spaces-spaceId-members1907927139": {
            /** @description 부여할 역할 */
            role?: string | null;
            /** @description 초대 대상 사용자 식별자 */
            userId?: string | null;
        };
        "v1-pages-pageId-comments-commentId-183646062": {
            /** @description 댓글 식별자＊ */
            commentId: string;
            /** @description 갱신된 본문＊ */
            body: string;
            /** @description 갱신 시각 (ISO)＊ */
            updatedAt: string;
        };
        "v1-pages-pageId1619565545": {
            /** @description 갱신된 제목＊ */
            title: string;
            /** @description 페이지 식별자＊ */
            pageId: string;
            /** @description 갱신 후 currentVersion＊ */
            version: number;
            /** @description 갱신 시각 (ISO)＊ */
            updatedAt: string;
        };
        "v1-spaces-spaceId1622365333": {
            /** @description 스페이스 식별자＊ */
            spaceId: string;
            /** @description 갱신된 공개 범위＊ */
            visibility: string;
            /** @description 갱신된 이름＊ */
            name: string;
            /** @description 갱신된 설명＊ */
            description: string;
            /** @description 갱신 시각 (ISO)＊ */
            updatedAt: string;
        };
        "v1-pages-pageId-revisions-154523481": {
            /** @description 페이지당 항목 수＊ */
            size: number;
            /** @description 결과 비어 있음 여부＊ */
            isEmpty: boolean;
            /** @description 총 페이지 수＊ */
            totalPages: number;
            /** @description 다음 페이지 존재 여부＊ */
            hasNext: boolean;
            /** @description 현재 페이지＊ */
            page: number;
            /** @description 리비전 목록＊ */
            items: {
                /** @description ⎯ 리비전 식별자＊ */
                revisionId: string;
                /** @description ⎯ 기록된 시각 (ISO)＊ */
                createdAt: string;
                /** @description ⎯ 작성자 식별자＊ */
                authorId: string;
                /** @description ⎯ 그 시점의 제목＊ */
                title: string;
                /** @description ⎯ 소속 페이지 식별자＊ */
                pageId: string;
                /** @description ⎯ 리비전 버전＊ */
                version: number;
            }[];
            /** @description 총 항목 수＊ */
            totalElements: number;
        };
        "v1-tags-1616429623": {
            /** @description 스페이스 식별자＊ */
            spaceId: string;
            /** @description 태그 이름＊ */
            name: string;
        };
        "v1-pages-1606830570": {
            /** @description 생성된 페이지 식별자＊ */
            pageId: string;
        };
        "v1-spaces-spaceId-tags546803558": {
            /** @description 페이지당 항목 수＊ */
            size: number;
            /** @description 결과 비어 있음 여부＊ */
            isEmpty: boolean;
            /** @description 총 페이지 수＊ */
            totalPages: number;
            /** @description 다음 페이지 존재 여부＊ */
            hasNext: boolean;
            /** @description 현재 페이지＊ */
            page: number;
            /** @description 태그 목록＊ */
            items: {
                /** @description ⎯ 생성 시각 (ISO)＊ */
                createdAt: string;
                /** @description ⎯ 소속 스페이스 식별자＊ */
                spaceId: string;
                /** @description ⎯ 태그 식별자＊ */
                tagId: string;
                /** @description ⎯ 태그 이름＊ */
                name: string;
            }[];
            /** @description 총 항목 수＊ */
            totalElements: number;
        };
        "v1-pages-pageId-comments-commentId378525178": {
            /** @description 수정된 본문＊ */
            body: string;
        };
        "v1-pages-pageId2116066709": {
            /** @description 생성 시각 (ISO)＊ */
            createdAt: string;
            /** @description 소속 스페이스 식별자＊ */
            spaceId: string;
            /** @description 공개 범위＊ */
            visibility: string;
            /** @description 부모 페이지 식별자 */
            parentPageId?: string | null;
            /** @description 제목＊ */
            title: string;
            /** @description 작성자 식별자＊ */
            authorId: string;
            /** @description 페이지 식별자＊ */
            pageId: string;
            /** @description 현재 버전＊ */
            currentVersion: number;
            /** @description 본문＊ */
            content: string;
            /** @description 최근 갱신 시각 (ISO)＊ */
            updatedAt: string;
        };
        "v1-spaces-spaceId-members-1854409151": {
            /** @description 페이지당 항목 수＊ */
            size: number;
            /** @description 결과 비어 있음 여부＊ */
            isEmpty: boolean;
            /** @description 총 페이지 수＊ */
            totalPages: number;
            /** @description 다음 페이지 존재 여부＊ */
            hasNext: boolean;
            /** @description 현재 페이지＊ */
            page: number;
            /** @description 멤버 목록＊ */
            items: {
                /** @description ⎯ 스페이스 식별자＊ */
                spaceId: string;
                /** @description ⎯ 역할＊ */
                role: string;
                /** @description ⎯ 가입 시각 (ISO)＊ */
                joinedAt: string;
                /** @description ⎯ 멤버 식별자＊ */
                spaceMemberId: string;
                /** @description ⎯ 사용자 식별자＊ */
                userId: string;
            }[];
            /** @description 총 항목 수＊ */
            totalElements: number;
        };
        "v1-pages-pageId-revisions-version1964469920": {
            /** @description 리비전 식별자＊ */
            revisionId: string;
            /** @description 기록된 시각 (ISO)＊ */
            createdAt: string;
            /** @description 작성자 식별자＊ */
            authorId: string;
            /** @description 그 시점의 제목＊ */
            title: string;
            /** @description 소속 페이지 식별자＊ */
            pageId: string;
            /** @description 리비전 버전＊ */
            version: number;
            /** @description 그 시점의 본문＊ */
            content: string;
        };
        "v1-pages365256445": {
            /** @description 페이지당 항목 수＊ */
            size: number;
            /** @description 결과 비어 있음 여부＊ */
            isEmpty: boolean;
            /** @description 총 페이지 수＊ */
            totalPages: number;
            /** @description 다음 페이지 존재 여부＊ */
            hasNext: boolean;
            /** @description 현재 페이지＊ */
            page: number;
            /** @description 검색 결과 목록＊ */
            items: {
                /** @description ⎯ 소속 스페이스 식별자＊ */
                spaceId: string;
                /** @description ⎯ 제목＊ */
                title: string;
                /** @description ⎯ 페이지 식별자＊ */
                pageId: string;
                /** @description ⎯ 최근 갱신 시각 (ISO)＊ */
                updatedAt: string;
            }[];
            /** @description 총 항목 수＊ */
            totalElements: number;
        };
        "v1-spaces1657775542": {
            /** @description 생성된 스페이스 식별자＊ */
            spaceId: string;
        };
        "v1-pages-pageId-comments618867481": {
            /** @description 페이지당 항목 수＊ */
            size: number;
            /** @description 결과 비어 있음 여부＊ */
            isEmpty: boolean;
            /** @description 총 페이지 수＊ */
            totalPages: number;
            /** @description 다음 페이지 존재 여부＊ */
            hasNext: boolean;
            /** @description 현재 페이지＊ */
            page: number;
            /** @description 댓글 목록＊ */
            items: {
                /** @description ⎯ 생성 시각 (ISO)＊ */
                createdAt: string;
                /** @description ⎯ 댓글 식별자＊ */
                commentId: string;
                /** @description ⎯ 본문＊ */
                body: string;
                /** @description ⎯ 작성자 식별자＊ */
                authorId: string;
                /** @description ⎯ 소속 페이지 식별자＊ */
                pageId: string;
                /** @description ⎯ 최근 갱신 시각 (ISO)＊ */
                updatedAt: string;
            }[];
            /** @description 총 항목 수＊ */
            totalElements: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "Page \uD398\uC774\uC9C0 \uAC80\uC0C9 \uC815\uC0C1 \uAC80\uC0C9 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: {
                /** @description 검색 키워드 (제목·본문, 대소문자 무시) */
                query?: string;
                /** @description 스페이스 ID 필터 */
                space?: string;
                /** @description 태그 ID 필터 (다중 시 AND 매칭) */
                tag?: string;
                /** @description 정렬 옵션 (CREATED_AT / UPDATED_AT / RELEVANCE, 기본값 UPDATED_AT) */
                sort?: string;
                /** @description 페이지 */
                page?: string;
                /** @description 페이지당 항목 수 */
                size?: string;
            };
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-pages365256445"];
                };
            };
        };
    };
    "Page \uD398\uC774\uC9C0 \uC0DD\uC131 \uC815\uC0C1 \uC0DD\uC131 \uC2DC 201 \uACFC pageId \uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["v1-pages-1087482196"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-pages-1606830570"];
                };
            };
        };
    };
    "Space \uC2A4\uD398\uC774\uC2A4 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: {
                /** @description 페이지 */
                page?: string;
                /** @description 페이지당 항목 수 */
                size?: string;
            };
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-spaces1523498116"];
                };
            };
        };
    };
    "Space \uC2A4\uD398\uC774\uC2A4 \uC0DD\uC131 \uC815\uC0C1 \uC0DD\uC131 \uC2DC 201 \uACFC spaceId \uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["v1-spaces-1862598174"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-spaces1657775542"];
                };
            };
        };
    };
    "Tag \uD0DC\uADF8 \uB4F1\uB85D \uC815\uC0C1 \uC0DD\uC131 \uC2DC 201 \uACFC tagId \uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["v1-tags-1616429623"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-tags-1141217090"];
                };
            };
        };
    };
    "Page \uD398\uC774\uC9C0 \uB2E8\uAC74 \uC870\uD68C \uC874\uC7AC\uD558\uBA74 200 \uACFC \uC815\uBCF4\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                pageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-pages-pageId2116066709"];
                };
            };
        };
    };
    "Page \uD398\uC774\uC9C0 \uC218\uC815 \uC81C\uBAA9\u00B7\uBCF8\uBB38 \uBCC0\uACBD \uC2DC 200 \uACFC \uAC31\uC2E0 \uACB0\uACFC\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                pageId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["v1-pages-pageId51781261"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-pages-pageId1619565545"];
                };
            };
        };
    };
    "Page \uD398\uC774\uC9C0 \uC0AD\uC81C \uC131\uACF5\uD558\uBA74 204 \uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                pageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Space \uC2A4\uD398\uC774\uC2A4 \uB2E8\uAC74 \uC870\uD68C \uC874\uC7AC\uD558\uBA74 200 \uACFC \uC815\uBCF4\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                spaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-spaces-spaceId-6516778"];
                };
            };
        };
    };
    "Space \uC2A4\uD398\uC774\uC2A4 \uC218\uC815 \uC774\uB984\u00B7\uC124\uBA85\uC744 \uBCC0\uACBD\uD558\uBA74 200 \uACFC \uAC31\uC2E0 \uACB0\uACFC\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                spaceId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["v1-spaces-spaceId175277175"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-spaces-spaceId1622365333"];
                };
            };
        };
    };
    "Space \uC2A4\uD398\uC774\uC2A4 \uC0AD\uC81C \uC131\uACF5\uD558\uBA74 204 \uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                spaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Tag \uD0DC\uADF8 \uC0AD\uC81C ADMIN \uC73C\uB85C \uD638\uCD9C\uD558\uBA74 204 \uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:ADMIN
                 */
                Authorization: string;
            };
            path: {
                tagId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Comment \uB313\uAE00 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: {
                /** @description 페이지 */
                page?: string;
                /** @description 페이지당 항목 수 */
                size?: string;
            };
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                pageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-pages-pageId-comments618867481"];
                };
            };
        };
    };
    "Comment \uB313\uAE00 \uB4F1\uB85D \uC815\uC0C1 \uC0DD\uC131 \uC2DC 201 \uACFC commentId \uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                pageId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["v1-pages-pageId-comments-225807540"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-pages-pageId-comments-1994389907"];
                };
            };
        };
    };
    "Page \uD398\uC774\uC9C0 \uB9AC\uBE44\uC804 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: {
                /** @description 페이지 */
                page?: string;
                /** @description 페이지당 항목 수 */
                size?: string;
            };
            header?: never;
            path: {
                pageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-pages-pageId-revisions-154523481"];
                };
            };
        };
    };
    "Tag \uD398\uC774\uC9C0 \uD0DC\uADF8 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: {
                /** @description 페이지 */
                page?: string;
                /** @description 페이지당 항목 수 */
                size?: string;
            };
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                pageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-spaces-spaceId-tags546803558"];
                };
            };
        };
    };
    "Tag \uD398\uC774\uC9C0\uC5D0 \uD0DC\uADF8 \uB9E4\uD551 \uC131\uACF5\uD558\uBA74 204 \uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                pageId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["v1-pages-pageId-tags1826217235"];
            };
        };
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "SpaceMember \uC2A4\uD398\uC774\uC2A4 \uBA64\uBC84 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: {
                /** @description 페이지 */
                page?: string;
                /** @description 페이지당 항목 수 */
                size?: string;
            };
            header?: never;
            path: {
                spaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-spaces-spaceId-members-1854409151"];
                };
            };
        };
    };
    "SpaceMember \uC2A4\uD398\uC774\uC2A4 \uBA64\uBC84 \uAC00\uC785 ": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                spaceId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["v1-spaces-spaceId-members1907927139"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-spaces-spaceId-members-472001083"];
                };
            };
        };
    };
    "Tag \uC2A4\uD398\uC774\uC2A4 \uD0DC\uADF8 \uBAA9\uB85D \uC870\uD68C \uC815\uC0C1 \uC751\uB2F5 \uC2DC 200 \uACFC \uD398\uC774\uC9C0\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: {
                /** @description 페이지 */
                page?: string;
                /** @description 페이지당 항목 수 */
                size?: string;
            };
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                spaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-spaces-spaceId-tags546803558"];
                };
            };
        };
    };
    "Comment \uB313\uAE00 \uB2E8\uAC74 \uC870\uD68C \uC874\uC7AC\uD558\uBA74 200 \uACFC \uC815\uBCF4\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                pageId: string;
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-pages-pageId-comments-commentId-1192310110"];
                };
            };
        };
    };
    "Comment \uB313\uAE00 \uC218\uC815 \uBCF8\uBB38 \uBCC0\uACBD \uC2DC 200 \uACFC \uAC31\uC2E0 \uACB0\uACFC\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                pageId: string;
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["v1-pages-pageId-comments-commentId378525178"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-pages-pageId-comments-commentId-183646062"];
                };
            };
        };
    };
    "Comment \uB313\uAE00 \uC0AD\uC81C \uC131\uACF5\uD558\uBA74 204 \uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                pageId: string;
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Page \uD398\uC774\uC9C0 \uB9AC\uBE44\uC804 \uB2E8\uAC74 \uC870\uD68C \uC874\uC7AC\uD558\uBA74 200 \uACFC \uC815\uBCF4\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pageId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-pages-pageId-revisions-version1964469920"];
                };
            };
        };
    };
    "Tag \uD398\uC774\uC9C0\uC5D0\uC11C \uD0DC\uADF8 \uB9E4\uD551 \uC81C\uAC70 \uC131\uACF5\uD558\uBA74 204 \uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                pageId: string;
                tagId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "SpaceMember \uC2A4\uD398\uC774\uC2A4 \uBA64\uBC84 \uC5ED\uD560 \uBCC0\uACBD \uC815\uC0C1 \uBCC0\uACBD \uC2DC 200 \uACFC \uAC31\uC2E0\uB41C \uBA64\uBC84 \uC815\uBCF4\uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                spaceId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["v1-spaces-spaceId-members-userId781967196"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1-spaces-spaceId-members-userId1005729910"];
                };
            };
        };
    };
    "SpaceMember \uC2A4\uD398\uC774\uC2A4 \uBA64\uBC84 \uC81C\uAC70 \uC131\uACF5\uD558\uBA74 204 \uB97C \uBC18\uD658\uD55C\uB2E4": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 토큰 (`Bearer {token}`)
                 * @example Bearer 100:USER
                 */
                Authorization: string;
            };
            path: {
                spaceId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
